reactiveWebGL <- function (outputId) 
{
  HTML(paste("<div id=\"", outputId, "\" class=\"shiny-webgl-output\"></div>", sep=""))
}

shinyUI(pageWithSidebar(    
  headerPanel("Plot 3D Points Online with WebGL"),
  
  sidebarPanel(
    tags$textarea(id="points", rows=10, cols=30, "1,1,1,\"#000000\"\n2,2,2,\"#000000\"\n3,3,3,\"#000000\"\n"),
    
    textInput("xlab", label="X-Axis Label:"),
    textInput("ylab", label="Y-Axis Label:"),
    textInput("zlab", label="Z-Axis Label:"),
    
    selectInput("type", "Plot Type", c("Scatterplot", "Line"), selected="Scatterplot"),
    
    HTML("<hr />"),
    helpText(HTML("All source available on <a href = \"https://github.com/trestletech/shiny-sandbox/tree/master/3dplot\">Github</a>"))
  ),
  
  
  mainPanel(        
    #Add our custom JS script which binds the custom WebGL type (just HTML)
    tags$head(tags$script(src="rgl.js", type="text/javascript")),
    #Add CanvasMatrix (needed for the WebGL generated by rgl)
    tags$head(tags$script(src="CanvasMatrix.js", type="text/javascript")),
    
    reactiveWebGL(outputId = "webGL")    
  )
))
