reactiveWebGL <- function (outputId) 
{
  HTML(paste("<div id=\"", outputId, "\" class=\"shiny-webgl-output\"></div>", sep=""))
}

googleAnalytics <- function(account="UA-36850640-1"){
  HTML(paste("<script type=\"text/javascript\">
    
    var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '",account,"']);
  _gaq.push(['_setDomainName', 'rstudio.com']);
  _gaq.push(['_trackPageview']);
  
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  
  </script>", sep=""))
}

#' Get the color palettes from RColorBrewer to display as options for the user.
getColorPalettes <- function(){
  #reach into RColor Brewer's var's to get the list of all the non-qualitative color palettes they offer
  c(RColorBrewer:::divlist,
    RColorBrewer:::seqlist)
}

shinyUI(pageWithSidebar(    
  headerPanel("WebGL Demo"),
  
  sidebarPanel(
    selectInput(inputId = "palette", label="Color Palette", choices=getColorPalettes()),
        
    checkboxInput(inputId= "PCA", label="Display principal components.", value=FALSE),
    conditionalPanel("input.PCA == true", 
      selectInput(inputId = "pcaCount", label="Principal components to display:", choices=1:3)      
    ),
                
    HTML("<hr />"),
    helpText(HTML("All source available on <a href = \"https://github.com/trestletech/shiny-sandbox/tree/master/rgl\">Github</a>"))
  ),
  
  
  mainPanel(        
    #Add our custom JS script which binds the custom WebGL type (just HTML)
    tags$head(tags$script(src="rgl.js", type="text/javascript")),
    #Add CanvasMatrix (needed for the WebGL generated by rgl)
    tags$head(tags$script(src="CanvasMatrix.js", type="text/javascript")),
    
    reactiveWebGL(outputId = "webGL"),    
    conditionalPanel("input.PCA == true", 
      textOutput(outputId="r2")
    ),
    googleAnalytics()
  )
))
