reactiveWebGL <- function (outputId) 
{
  HTML(paste("<div id=\"", outputId, "\" class=\"shiny-webgl-output\"></div>", sep=""))
}

#' Get the color palettes from RColorBrewer to display as options for the user.
getColorPalettes <- function(){
  #reach into RColor Brewer's var's to get the list of all the non-qualitative color palettes they offer
  c(RColorBrewer:::divlist,
    RColorBrewer:::seqlist)
}

shinyUI(pageWithSidebar(    
  headerPanel("WebGL Demo"),
  
  sidebarPanel(
    selectInput(inputId = "palette", label="Color Palette", choices=getColorPalettes()),
        
    checkboxInput(inputId= "PCA", label="Display principal components.", value=FALSE),
    conditionalPanel("input.PCA == true", 
      selectInput(inputId = "pcaCount", label="Principal components to display:", choices=1:3)      
    ),
                
    HTML("<hr />"),
    helpText(HTML("All source available on <a href = \"https://github.com/trestletech/shiny-sandbox/tree/master/rgl\">Github</a>"))
  ),
  
  
  mainPanel(        
    #Add our custom JS script which binds the custom WebGL type (just HTML)
    tags$head(tags$script(src="rgl.js", type="text/javascript")),
    #Add CanvasMatrix (needed for the WebGL generated by rgl)
    tags$head(tags$script(src="CanvasMatrix.js", type="text/javascript")),
    
    reactiveWebGL(outputId = "webGL"),    
    conditionalPanel("input.PCA == true", 
      textOutput(outputId="r2")
    )
  )
))
