#' Extracts the relevant <canvas> sections from the HTML document produced via
#' a call to writeWebGL().
#' 
#' The resultant HTML document will work assuming that canvasMatrix.js is loaded
#' and that webGLStart() is called.
extractWebGL <- function(wwwDir="www", imgDir="img/"){
  #generate a random 10 character sequence to represent this file
  id <- paste(sample(c(letters, LETTERS), 10), collapse="")  
  tempDir <- paste(tempdir(), "/", id, "/", sep="")
  
  writeWebGL(dir=tempDir)

  #read in the file and extract only the canvas elements.
  lines <- readLines(paste(tempDir, "/index.html", sep=""))
  lines <- lines[-(1:7)]
  lines <- lines[-((length(lines)-8):length(lines))]
  
  #sub out the snapshot reference for a file with a unique ID
  lines <- gsub("snapshot.png", paste(imgDir, id, ".png", sep=""), lines)
  
  #copy the snapshot image to a public WWW dir
  file.copy(paste(tempDir, "snapshot.png", sep=""), paste(wwwDir, "/", imgDir, id, ".png", sep=""))
  
  #remove the temporary directory
  #TODO: Doesn't seem to work in Windows
  unlink(tempDir, recursive=TRUE)
  
  #return the HTML lines generated by RGL
  paste(lines, collapse="\n")
}
